### ISSUE TITLE
Hook priority/weight

### ISSUE THREAD

**Issue by edouardpoitras** [getslash/gossip#21]
Hello. Great job on this library! Very feature rich and easy to use.

I'm wondering if there's a way of specifying priority or weights when registering hooks. The provides/needs capabilities are not quite what I'm looking for. Glancing at the source code it seems there isn't a way of doing this in gossip, but maybe someone knows of a work-around?

This, and collecting all hook return values, are the only two things stopping me from completely ditching the blinker library.

**Comment by vmalloc** [comment]
@edouardpoitras can you give examples for why you need these two features? It would help me understand how to address them.

Thanks!

**Comment by edouardpoitras** [comment]
Hey @vmalloc,

My specific scenario is that I have an application that will allow for plugins to hook in at various parts of the execution. The majority of these plugins will be from 3rd parties, and these 3rd parties can in-turn set their own hook triggers. I can't assume that they will set their own needs/provides.
I suppose I could enforce that with plugin development standards and documentation.

Even so, what if I'm creating another 3rd party plugin that depends on the first 3rd party plugin. I know I want this plugins to hook into the original 3rd party plugin hook, but I also would prefer it run before any other plugin attempt to hook into that same spot. Although if another plugin comes around and they know what they're doing, they can go first.

Some of these scenarios require the 3rd party plugins to coordinate amongst each other and add provides/needs as required (or even entirely new pre/post hooks). That's what I'm trying to remove the need for.

Maybe I'm missing something and there's a better way of accomplishing this. I've already committed to gossip at this point as I think it's still superior to blinker. I just felt my framework would be more flexible and easier on plugin developers if they could specify an approximation of priority when registering hooks.

By the way, I'm getting around the whole 'collecting the return values' thing by just passing a dict reference in the hooks. This allows plugins to modify the dict as needed to pass information back to the triggering function.

**Comment by vmalloc** [comment]
Ok, so I can add an optional weight and make sure it is stable-sorted as to not affect current clients. I guess it couldn't hurt much...

**Comment by vmalloc** [comment]
@edouardpoitras please check out the develop branch and see if the new priorities feature is what you're looking for.

For reference, see http://gossip.readthedocs.io/en/latest/hook_dependencies.html#using-numerical-priorities

**Comment by edouardpoitras** [comment]
Outstanding! That is exactly what I was looking for.
I can confirm that this does indeed works as expected on the develop branch.

Thank you :)
