### ISSUE TITLE
Adding registration context

### ISSUE THREAD

**Issue by ayalash** [getslash/gossip#28]
The code of hook registration for specific code block looks not elegant.
Currently there are two options for doing it:
```
hook = gossip.get_hook('my_hook')
reg = hook.register(func)
... # Code block
reg.unregister
```
or
```
goossip.register(func, 'my_hook', token='some_token')
... # Code block
gossip.unregister_token('some_token')
```
It would be nice to have:
```
with gossip.registrated(fun, 'my_hook'):
    ... # Code block
```

**Comment by ayalash** [comment]
@vmalloc What do you think?

**Comment by vmalloc** [comment]
I'm in favor, only the name should change. Registrated isn't a word.

Perhaps `with.gossip.registering(func, 'myhook')`

**Comment by vmalloc** [comment]
Sorry, a better name would be `registered`, since at the end of the context it gets unregistered...
